### ISSUE TITLE
Sysadmin dashboard conversion ADRs

### ISSUE THREAD

**Issue by arbrandes** [openedx/community-wg#10]
@pdpinch has produced two preliminary ADRs on the subject:

https://github.com/edx/edx-platform/pull/23697
https://github.com/edx/edx-platform/pull/24048

[(Original issue)](https://trello.com/c/vkXNSu2X)

**Comment by arbrandes** [comment]
@pdpinch, I think the description is missing the end goal, here.  Or is this complete?

**Comment by pdpinch** [comment]
This issue is complete. The ADRs have been merged, the sysadmin dashboard has been deprecated and is now removed. 

We are working on a [plugin](https://github.com/mitodl/edx-sysadmin/) that will replace the sysadmin dashboard's functionality, as outlined in the ADRs.
