### ISSUE TITLE
Empower CC Community to Improve Onboarding Course

### ISSUE THREAD

**Issue by cassiezamparini** [openedx/community-wg#129]
[See proposal](https://openedx.atlassian.net/wiki/spaces/COMM/pages/4490526764/Empower+CC+Community+to+Improve+Onboarding+Course)

**Comment by sarina** [comment]
The course is now available at https://github.com/openedx/training-courses and all coding core contributors are collaborators on the course. I have marked myself as maintainer of the repo and will be monitoring for PRs.
