### ISSUE TITLE
Coordinate the Core Contributor Program

### ISSUE THREAD

**Issue by arbrandes** [openedx/community-wg#13]
Assist in coordinating the [Core Committer Program](https://github.com/orgs/edx/projects/1).

**Comment by arbrandes** [comment]
(Apologies for the accidental assignee flapping.)

**Comment by nasthagiri** [comment]
Adding @sarina.

**Comment by antoviaque** [comment]
@sarina I believe you're the one owning this now, right? I'll update the assignee.

**Comment by antoviaque** [comment]
@sarina Yup, that's exactly it :) It doesn't involve doing any work you aren't already doing imho.

**Comment by sarina** [comment]
Closing this out, the CC program is running pretty smoothly with Xavier, Dean, and myself all taking responsibilities for various activities.
