### ISSUE TITLE
Find assignees for all roles in the build-test-release workgroup

### ISSUE THREAD

**Issue by arbrandes** [openedx/community-wg#16]
See [this PR](https://github.com/openedx/build-test-release-wg/pull/13) for the associated ADRs and role descriptions.

**Comment by arbrandes** [comment]
Should this issue live here, or on the BTR board?

**Comment by antoviaque** [comment]
@arbrandes This would be more of an internal BTR task I think? Also, this looks done now right?

**Comment by arbrandes** [comment]
That's right - this is totally an internal BTR task.  But I was experimenting with using an issue here as a way to communicate what's happening there.
