### ISSUE TITLE
Contributors Meetup 2021-02-22

### ISSUE THREAD

**Issue by arbrandes** [openedx/community-wg#17]
## Date, time, and location

Monday February 22nd 2021, 15:00 UTC ([time converter](https://www.timeanddate.com/worldclock/fixedtime.html?msg=Open+edX+Contributors+Meetup&iso=20210222T15&p1=1440&ah=1)) 

* [ical](https://calendar.google.com/calendar/ical/c_mvh2oito7s9n89g5nnkk49psks%40group.calendar.google.com/public/basic.ics)
* [gcal](https://calendar.google.com/calendar/embed?src=c_mvh2oito7s9n89g5nnkk49psks%40group.calendar.google.com)

## Agenda

Anyone can add additional agenda items by replying in the comments below, or on the [discourse forum thread](https://discuss.openedx.org/t/open-edx-contributors-meetup/1450).

* Intro
  * Meet & greet newcomers if any
  * Recap of the items in this agenda: anything to add or remove?
* Moving to the [github board](https://github.com/openedx/community-wg/projects/1) (@arbrandes)
  * Did not copy: backlog, completed, marketing, or issues that haven't seen activity in 6 months.
  * What's missing that should be brought in?
  * Move it to the edx org?
* [Documentation Efforts](https://github.com/openedx/community-wg/projects/1?card_filter_query=label%3Adocumentation)
   * [Doc-a-thon](#7)  (@regisb, @robrap)
   * [Dev Onboarding Courses](#11) (@OmarIthawi)
   * Dev Docs Project (Amy Brown, @robrap)
* Marketing WG update (Nicole Kessler, Stefania Trabucchi)
* Release WG update (@arbrandes, @BbrSofiane, @nedbat)
  * [New standard installation](#8)
  * [Looking for Release Documentation Expert, Community Liaison, and Head of edx/configuration](#16)
  * Definite plan for Lilac will be drafted this week
* [Core Committer program](#13)
  * [Org declaration of commitment](https://github.com/edx/open-edx-proposals/issues/172#issuecomment-738894477) (@nasthagiri)
  * A look at the [CC board](https://github.com/orgs/edx/projects/1) (@nasthagiri)
* Development discussion
  * [Improving Community-run CD](#15) (@arbrandes)
  * [Hook-based extensions](#5) (@felipemontoya)
  * [Sysadmin dashboard ADRs](#10) (@pdpinch)
* [Sprint planning](https://github.com/openedx/community-wg/projects/1)
  * Find assignees for every issue.

## Forum thread

https://discuss.openedx.org/t/open-edx-contributors-meetup/1450

## To join

Subscribe to the [calendar](https://calendar.google.com/calendar/ical/c_mvh2oito7s9n89g5nnkk49psks%40group.calendar.google.com/public/basic.ics), find the meeting, and click on the join URL!

## Video recording & chat log

* [Video](https://drive.google.com/file/d/1nmGUhKe4GlpMXB2CvSG0i_NLfYSE_Vcp/view?usp=sharing)
* [Chat](https://drive.google.com/file/d/1mEFqwiEvBq7i0gMDyxKcoLaGgZT6FDXG/view?usp=sharing)

**Comment by OmarIthawi** [comment]
@arbrandes Thanks for sharing. I will be giving a brief about the progress of the introduction course with a mention of the need to pick a good license.

**Comment by arbrandes** [comment]
Thanks @OmarIthawi, that'd be great! 👍🏼
