### ISSUE TITLE
Contributors Meetup 2021-03-08

### ISSUE THREAD

**Issue by arbrandes** [openedx/community-wg#18]
## Date, time, and location

Monday March 8th at 15:00 UTC ([Timezone converter](https://www.timeanddate.com/worldclock/fixedtime.html?msg=Open+edX+Contributors+Meetup&iso=20210308T15&p1=1440&ah=1))

* [ical](https://calendar.google.com/calendar/ical/c_mvh2oito7s9n89g5nnkk49psks%40group.calendar.google.com/public/basic.ics)
* [gcal](https://calendar.google.com/calendar/embed?src=c_mvh2oito7s9n89g5nnkk49psks%40group.calendar.google.com)

## Agenda

Anyone can add additional agenda items by replying in the comments below, or on the [discourse forum thread](https://discuss.openedx.org/t/open-edx-contributors-meetup/1450).

* Intro
  * Meet & greet newcomers if any
  * Recap of the items in this agenda: anything to add or remove?
* [Documentation Efforts](https://github.com/openedx/community-wg/projects/1?card_filter_query=label%3Adocumentation)
   * [Doc-a-thon](#7)  (@regisb, @BbrSofiane)
   * [Dev Onboarding Courses](#11) (@OmarIthawi)
   * Dev Docs Project: [Survey Results](https://openedx.atlassian.net/wiki/spaces/AC/pages/2445476472/Developer+Documentation+and+Training+Survey+Results+-+2021-Jan) (Amy Brown, @robrap, @nasthagiri)
* Marketing WG update (Nicole Kessler, Stefania Trabucchi)
* Release WG update (@arbrandes, @BbrSofiane, @nedbat)
  * [New standard installation](#8)
  * [Looking for Release Documentation Expert, Community Liaison, and Head of edx/configuration](#16)
  * Definite plan for Lilac
* [Core Committer program](#13)
  * [Org declaration of commitment](https://github.com/edx/open-edx-proposals/issues/172#issuecomment-738894477) (@nasthagiri)
  * A look at the [CC board](https://github.com/orgs/edx/projects/1) (@nasthagiri)
* Development discussion
  * [Improving Community-run CD](#15) (@arbrandes)
  * [Hook-based extensions](#5) (@felipemontoya)
  * [Sysadmin dashboard ADRs](#10) (@pdpinch)
* [Sprint planning](https://github.com/openedx/community-wg/projects/1)
  * Find assignees for every issue.

## Forum thread

https://discuss.openedx.org/t/open-edx-contributors-meetup/1450

## To join

Subscribe to the [calendar](https://calendar.google.com/calendar/ical/c_mvh2oito7s9n89g5nnkk49psks%40group.calendar.google.com/public/basic.ics), find the meeting, and click on the join URL!

## Video recording & chat log

* [Video](https://drive.google.com/file/d/1FHBelt3X05e0VUbqh0kfCr8ZrFSeIQaK/view?usp=sharing)
* [Chat](https://drive.google.com/file/d/1W32767N2p6N54x-O-JTnjaoR2RD1fr5z/view?usp=sharing)

**Comment by pdpinch** [comment]
Agenda Item: we recently discovered what we would consider a [breaking change to the grades API](https://github.com/edx/edx-platform/commit/68ec2e184d1b4ed7824954e34c97bef39647ebe2), which was part of the Juniper release. I'd like to discuss a few things:
1. Does anyone else consider this a breaking change?
2. If this is a breaking change, how should it have been communicated?
3. Is there anything we should do to communicate this particular change now?
