### ISSUE TITLE
Create core committer video

### ISSUE THREAD

**Issue by arbrandes** [openedx/community-wg#23]
Create a core committer video to go along with the upcoming blog post.

**Comment by arbrandes** [comment]
@nasthagiri, can you point me to the existing core committer videos you mentioned in the meeting?  And to the content of the upcoming blog post, so I can get the gist?

**Comment by arbrandes** [comment]
Status update: I haven't had time to do this yet, and I'm taking Mar 22 - Mar 29 off, but I'll get to it when I get back.

**Comment by arbrandes** [comment]
I'm targetting this for delivery this week.

**Comment by arbrandes** [comment]
And now this week. 😅

**Comment by nizarmah** [comment]
@arbrandes any context you can provide on this? Is it something that should still be done, or not?

**Comment by arbrandes** [comment]
@nizarmah, the idea was to create a marketing-style video to go with the core contributor program announcement, but I was never able to get something decent made with the time I had available.  Perhaps unsurprisingly, this kind of thing is better done by professionals. :)

It's fine to close this.
