### ISSUE TITLE
Contributor's Meetup 2021-11-16

### ISSUE THREAD

**Issue by antoviaque** [openedx/community-wg#44]
## Date, time, and location

Tuesday November 16th at 15:00 UTC ([Timezone converter](https://www.timeanddate.com/worldclock/fixedtime.html?msg=Open+edX+Contributors+Meetup&iso=20211116T15&p1=1440&ah=1))

* [ical](https://calendar.google.com/calendar/ical/c_mvh2oito7s9n89g5nnkk49psks%40group.calendar.google.com/public/basic.ics)
* [gcal](https://calendar.google.com/calendar/embed?src=c_mvh2oito7s9n89g5nnkk49psks%40group.calendar.google.com)

## Agenda

Anyone can add additional agenda items by replying in the comments below, or on the [discourse forum thread](https://discuss.openedx.org/t/open-edx-contributors-meetup/1450).

### 1. Intro

* Meet & greet newcomers if any
* Recap of the items in this agenda: anything to add or remove?
* Request members participate in the contributor meetup [whenisgood poll](https://discuss.openedx.org/t/open-edx-contributors-meetup/1450/75?u=nizar).

### 2. Working group updates

* Marketing (@nedbat)
* Release (@BbrSofiane, @nedbat, @regisb)
* [Frontend](https://discuss.openedx.org/t/announcing-the-frontend-working-group/5769) (@davidjoy)
* [Core Contributors](https://github.com/openedx/community-wg/issues/13) (@sarina)
* [Data](https://github.com/orgs/openedx/projects/5) (@blarghmatey, @e0d)

### 3. Events

* Open edX Virtual Event in December

#### Higher Priority

* [Core contributors sprints](https://github.com/openedx/community-wg/issues/43) (@antoviaque)
* edX Brandings Backlog (@e0d) - continue discussion
* [Upgrades](https://docs.google.com/spreadsheets/d/11DheEtMDGrbA9hsUvZ2SEd4Cc8CaC4mAfoV8SVaLBGI/edit#gid=1850889545)
  * [Django 3.2 upgrade](https://openedx.atlassian.net/wiki/spaces/AC/pages/3073376294/Django+3.2+Upgrade+How+the+Community+Can+Help) - check if we have any updates regarding the number of tickets tackled by non edX members 
  * [Node.js 16](https://github.com/openedx/frontend-wg/issues/2)
* Django Backend APIs: [Django Signal Events](https://discuss.openedx.org/t/configuration-for-the-hooks-extension-framework/4527), [Django Filters](https://discuss.openedx.org/t/hooks-framework-filters/5753) (@felipemontoya)
* [xAPI/Caliper](https://openedx.atlassian.net/wiki/spaces/COMM/pages/1863516315/xAPI+Caliper+Implementation), [OEP-26](https://open-edx-proposals.readthedocs.io/en/latest/oep-0026-arch-realtime-events.html) (@ziafazal)
* [MySQL instead of MongoDB](https://github.com/edx/edx-platform/pull/27565)
* [DEPR](https://openedx.atlassian.net/browse/DEPR) impediments - any tickets that need real-time discussion?
  * [Entrance Exam](https://openedx.atlassian.net/browse/DEPR-163) - how can we remove this unsupported feature from the core?
  * [Replace the Ecommerce Application](https://openedx.atlassian.net/browse/DEPR-169) - start the discussion
* [Tech Radar] We're live! Announcement: https://discuss.openedx.org/t/the-open-edx-tech-radar-is-live/6042
* [MFE theming](https://github.com/openedx/community-wg/issues/42) (@xitij2000)
 
#### Lower Priority

* [Dev Onboarding Courses](https://github.com/openedx/community-wg/issues/11) (@OmarIthawi)
* [Contribution Course](https://gitlab.com/opencraft/documentation/mooc-floss) (@antoviaque)
* [Contributor t-shirt](https://github.com/openedx/community-wg/issues/24) (@gabrieldamours)
* [Leaderboard](https://github.com/edx/open-edx-proposals/issues/179) (@e0d, @pomegranited)

### 5. Time permitting

* Review [the board](https://github.com/openedx/community-wg/projects/1)

## Forum thread

https://discuss.openedx.org/t/open-edx-contributors-meetup/1450

## To join

Subscribe to the [calendar](https://calendar.google.com/calendar/ical/c_mvh2oito7s9n89g5nnkk49psks%40group.calendar.google.com/public/basic.ics), find the meeting, and click on the join URL!

## Video recording & chat log

* [Video](https://drive.google.com/file/d/1AvXNYx1Nszz2PXgauz2pbLKs7xGe3gSh/view?usp=sharing)
* [Chat](https://drive.google.com/file/d/1DRf_kibojoJr-bF3KDAxy37Vvn3ZnJVY/view?usp=sharing)
* [Text Overview](https://discuss.openedx.org/t/open-edx-contributors-meetup/1450/76?u=nizar)

**Comment by antoviaque** [comment]
@nizarmah I've cloned the agenda from the last meetup, as @pdpinch was asking about it. Can I let you update it if needed?

Also I think we still need to figure out whether we keep the meeting time, with the timezone changes.

**Comment by nizarmah** [comment]
@antoviaque done 👍🏼 

Also, I apologize to all members regarding the delay.

**Comment by nizarmah** [comment]
My bad. Moving this back to "In Progress" until the text overview and the recording are provided.
