### ISSUE TITLE
Participate in the doc-a-thon

### ISSUE THREAD

**Issue by arbrandes** [openedx/community-wg#7]
The group should spread the word and continuing to participate in the [doc-a-thon](https://tinyurl.com/doc-a-thon-2021).

Potential assignees:
* @robrap
* @regisb

**Comment by antoviaque** [comment]
@arbrandes This seems like something currently in progress?

**Comment by robrap** [comment]
If this is about spreading the word for the doc-a-thon, I think @nasthagiri could help provide input on who owns this. I'm no longer actively involved in the effort, except if I need to provide support to someone.

**Comment by arbrandes** [comment]
A note for the next meeting: Natalia [asked on Slack about ideas](https://openedx.slack.com/archives/C01KL48HFNF/p1615947690005800), and I suggested having a monthly doc contribution leaderboard.
